---
title: Chemistry
date: 2024-07-27
draft: true
toc: true
number-sections: true
number-depth: 1
categories: [English]
---

# Elements

+-------------+-------------+----------------------------+-------------------------------+
| hydrogen    | 氢 (H)      | -   hydrogenic: 氢的       | -   carbohydrates: 碳水化合物 |
|             |             |                            |                               |
|             |             | -   hydrogenate: 使...氢化 |                               |
|             |             |                            |                               |
|             |             | -   hydrate: 水化物        |                               |
+-------------+-------------+----------------------------+-------------------------------+
| helium      | 氦 (He)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| lithium     | 锂 (Li)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| beryllium   | 铍 (Be)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| boron       | 硼 (B)      |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| carbon      | 碳 (C)      | -   carbo-: 碳的           | -   carbohydrates: 碳水化合物 |
|             |             |                            |                               |
|             |             | -   carbonate: 碳酸盐      |                               |
+-------------+-------------+----------------------------+-------------------------------+
| nitrogen    | 氮 (N)      |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| oxygen      | 氧 (O)      |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| fluorine    | 氟 (F)      |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
| neon        | 氖 (Ne)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
|             | 钠 (Na)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
|             | 镁 (Me)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
|             | 铝 (Al)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
|             | 硅 (Si)     |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+
|             | 磷 (P)      | -   phosphate: 磷酸盐      |                               |
+-------------+-------------+----------------------------+-------------------------------+
| sulphur     | 硫 (S)      | -   sulphite: 硫化物       |                               |
+-------------+-------------+----------------------------+-------------------------------+
|             |             |                            |                               |
+-------------+-------------+----------------------------+-------------------------------+

# Inorganics

## ammonium

ammonium

:   铵

    nitrite

    nitrite

    :   亚硝酸盐

    compound

    compound

    :   混合物

# Organics

## mono-

mono-

:   单

## poly-

poly-

:   多, 复合, 聚

    ## di-

    di-

    :   二

    ## tri-

    tri-

    :   三

# Nutrition

Omega 3

## protein

protein

:   蛋白质

collagen

collagen

:   胶原蛋白

lecithin

lecithin

:   卵磷脂

## fibre

fibre

:   纤维, 也可以指膳食纤维

mineral

mineral

:   矿物质

glucose

glucose

:   葡萄糖

## lactose

lactose

:   乳糖

1.  lactose intolerance (乳糖不耐症)

## fructose

fructose

:   左旋糖

## dextrose

dextrose

:   右旋糖

1.  polyunsaturates (多不饱和脂肪酸)

# Food Additive

+-------------------+---------------+----------------------+-------------------------+
| preservative      | 防腐剂        | -   sulphite: 硫化物 |                         |
+-------------------+---------------+----------------------+-------------------------+
| flavouring        | 调味剂        |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| raising agents    | 膨松剂        |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| stabiliser        | 稳定剂        |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| bulking agents    | 填充剂        |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
|                   |               |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| 1.  emulsifier    | 1.  (乳化剂)  |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| acidity regulator | 酸度调节剂    |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| 1.  antioxidant   | 抗氧化剂      |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| ##                | 甜味剂        |                      | ## aspartame            |
|                   |               |                      |                         |
| sweetener         |               |                      | 阿斯巴甜                |
|                   |               |                      |                         |
| :                 |               |                      |                         |
+-------------------+---------------+----------------------+-------------------------+
| humectant         | 保湿剂        |                      | 甘油: glycerine         |
+-------------------+---------------+----------------------+-------------------------+
| gelling agents    | 胶凝剂        |                      | 果胶: pectin            |
+-------------------+---------------+----------------------+-------------------------+
| firming agents    | 硬化剂        |                      | calcium lactate: 乳酸钙 |
+-------------------+---------------+----------------------+-------------------------+
| Flavour Enchancer |               |                      | monosodium glutamate    |
+-------------------+---------------+----------------------+-------------------------+
| thickener         |               |                      | xanthan gem             |
+-------------------+---------------+----------------------+-------------------------+
| anti-caking agent |               |                      |                         |
+-------------------+---------------+----------------------+-------------------------+

lycopene

maltodextrin: 麦芽糊精

inulin: 菊粉

oleic

1.

## concentrate

concentrate

:   浓缩液

## gum

gum

:   胶

## whey

whey

:   乳清

## xanthan

xanthan

:   黄原胶

raising agents (膨松剂)

## extract

extract

:   提取

1.  vanilla extract (香草精)

## sucralose

三氯蔗糖

## carotene

胡萝卜素

## carbonate

carbonated water

## caffeine

咖啡因

## citrate

柠檬酸盐

## niacin

niacin

:   烟酸

## nitrate

硝酸盐

## carrageenan

## folic acid

叶酸

## calorie

## fluoride

氟化物

## caramelise

## hoop

## malic

## lactic

maltitol syrup 麦芽糖家

molasses

mirin

tamarind

Hydrolysed
