---
title: English expressions miscellaneous
description: English expressions I've learned that don't fit into any category.
date: 2024-07-27
draft: true
toc: true
number-sections: true
number-depth: 1
categories: [English]
---

## 've got

’ve got:
: 有, 相当于 have. have 是书面语, ‘ve got 是口语. 下次想说 I have 的时候记得换成 ’ve got

1. I've got a lot of things to do today.
2. Have you got a charger I could borrow?

## It's best ...

It's best to do sth
: 最好...



## I would say

..., I would say
: 我会说

## handy

convenient?

## dodgy

## for ages

## not to mention

## unsurprisingly

## Obviously

当然了, ...

## kind of / sort of

## like

I was like

在英语口语中，“like” 经常用作填充词（filler word），帮助说话者思考或使语言更随意和自然。以下是一些使用“like”作为填充词的例子：

	1.	帮助思考：
	•	中文：我昨天，呃，去了超市。
	•	英文：I, like, went to the supermarket yesterday.
	2.	使语言更随意：
	•	中文：那部电影，呃，真的很好看。
	•	英文：That movie was, like, really good.
	3.	表达不确定性或约数：
	•	中文：我花了大约，呃，五十块钱。
	•	英文：I spent, like, fifty dollars.
	4.	用于举例或解释：
	•	中文：我们可以做一些活动，呃，比如，去爬山或者野餐。
	•	英文：We can do some activities, like, hiking or having a picnic.

需要注意的是，尽管“like”作为填充词在口语中很常见，但在正式的写作或演讲中应尽量避免过度使用，以保持语言的简洁和专业。



## for the best

for the best
: 终究有好处. 表达虽然现在看起来不太让人满意, 但是从长远看是有好处的.

1. Ending a relationship is always hard but in this case it's for the best.
2. Joe Biden said he stepped down from the presidency for the best interests of the American people.



## work the best

work the best for
: ...对...是最好的/有效的, 这样表达最简洁. 下次说 ... is the best... 可以换成 work the best

1. Let me know which plan works the best for you.


## just a reminder

just a reminder
: 就提醒一下.

1. Just a reminder, tomorrow is the deadline.

## It's really seen as
