---
title: Configure Your CL Dataset
---

The **continual learning dataset** is a sequence of datasets corresponding to continual learning tasks, each of which has their own training and testing data. If you are not familiar with continual learning datasets, feel free to get some knowledge from my [CL beginner's guide](../../../../posts/continual-learning-beginners-guide.qmd#CL-dataset).

To configure the continual learning dataset for your experiment, link the `cl_dataset` field in the main YAML file to sub-config file in the sub-directory [<your-config-dir>/cl_dataset/](https://github.com/pengxiang-wang/continual-learning-arena/tree/main/clarena/example_configs/cl_dataset/) of your configs, and specify the class and its arguments in the sub-config. In this package we pre-defined many CL dataset classes in `clarena.cl_datasets`, see the full list below.

Here is an example:

```plain
./clarena/example_configs
├── __init__.py
├── entrance.yaml
├── experiment
│   ├── example.yaml
│   └── ...
├── cl_dataset
│   └── permuted_mnist.yaml
...
```

```{.yaml filename="example_configs/experiment/example.yaml"}
defaults:
  ...
    - /cl_dataset: permuted_mnist.yaml
  ...
```

```{.yaml filename="example_configs/cl_dataset/permuted_mnist.yaml"}
_target_: clarena.cl_datasets.PermutedMNIST
root: data/MNIST
num_tasks: 10
validation_percentage: 0.1
batch_size: 64
num_workers: 10
```



# Supported Dataset List {#list}

Here is the full list of supported CL datasets so far. To select a dataset, replace with the class name. Please refer to the documentation of each class to know what fields (arguments) are required for the class.


| CL Dataset  |   Class Name | Description       |
| :----------------------------------------------------------- |:----------------------------------------------------------- |:----------------------------------------------------------- |
| Permuted MNIST  | PermutedMNIST | A [MNIST](http://yann.lecun.com/exdb/mnist/) variant for CL by random permutation of the input pixels to form differenet tasks   |
| Split MNIST |SplitMNIST | A MNIST variant for CL by spliting the dataset by class to form different tasks |
| Permuted CIFAR10 |   PermutedCIFAR10      | A [CIFAR](https://www.cs.toronto.edu/~kriz/cifar.html)-10 permuted variant for CL  |
| Split CIFAR100 | SplitCIFAR100  | A CIFAR-100 split variant for CL  |
