---
title: Shawn's Testimony of Christian Faith
description: Here is my testimony scripts in various occasions. I'd like to share my journey to faith with you here. 
date: 2024-10-24
draft: false
categories: [testimony]
---

# Baptism Testimony (01/12/2024)

## English

Good afternoon everyone, I am Shawn. I am very happy and grateful to share my testimony here. I am a visiting PhD student from Beijing, China, and have been in the UK for almost a year. Though brief, it has been the most meaningful experience of my life, that I discovered the light of life. My life is enviable yet extremely fragile, carefully wrapped in perfectionism and a singular set of values, pushing forward with almost no sense of security. I would temporarily gain immense satisfaction from my achievements, but the loss of security often replaced it with long-lasting anxiety, loneliness, confusion, and fear of the future. At one point, I felt that nothing made sense, and everything I did was so tiring and forced, just like maintaining a machine to keep it running without stopping.

In this darkness, I came to Bristol, and out of curiosity about the church and Christians, I began my exploration bit by bit. Initially, I attended various activities, Alpha courses, and camps with a mindset of "checking in". I met Christian friends, participated in fellowship, but behind the excitement was still anxiety and even forced; however, during this process, for the first time I heard Jesus say: “I am the light of the world. Whoever follows me will not walk in darkness, but will have the light of life.” (John 8:12) As I began to understand God, He continually surprised me, working in ways I could never have imagined. In an ocean of God’s love and the love of brothers and sisters, God spoke to me in various ways, reasoning and colliding in my extremely rational and logical brain which is studying maths and engineering, ultimately not arrogantly refuting that it's absurd, but slowly removing obstacles before the truth, making me more firmly willing to follow Jesus Christ, opening my eyes to see that He is the way, the truth, and the life. I was amazed to find that this beam of light illuminated every corner of mine, none left out, from everyday life, academics, relationships, to my view of life, world and value. Many people also noticed that my mind has matured a lot, understanding more about what love is, more passion for life, facing big and small things calmly, and caring for others. Some of these were changes that I had resolved to make myself, but I ultimately found that these changes were not made through my fleshly efforts or the ruthless logic of a Chinese saying “those who are near vermillion turn red, those who are near ink turn black”, but solely because of the complete reign of God and His love for me.

Today, I am baptised before returning to China. It's a testimony of my faith, a way of strengthening my belief, and a loud declaration that I am a new creation, no longer myself, but Christ living in me. I am very grateful to God for His loving care this year, for letting me meet Him, and more importantly, for letting me know that my future life is limitless in Him. Returning to China, I may face many difficulties: people face temptations, the environment seduces people to worship visible power, money, and fame; I may fall into weakness, dominated by anxiety and fear, disappointed by societal fragmentation, isolating myself by hypocrite masks, and being hesitant about faith; or I may fall into stubbornness and arrogance, continuing to dominate my pursuit of secular success with the mind of crude and selfish laws of the jungle, then going around in circles back to the lowlands of security and sense of value. But I deeply know that God will say with His love and power, “fear not, for I am with you; be not dismayed, for I am your God; I will strengthen you, I will help you, I will uphold you with my righteous right hand.” (Isaiah 41:10) If I live out the likeness of Jesus Christ, surely more people will follow Him, receiving His love. My firm belief will also cause more people to believe in Him, allowing more light to shine into the dark corners!

Thank God, and thank you all for listening!

## Chinese

大家下午好，我是Shawn。很高兴也很感恩在这里分享我的见证。我是来自中国北京的一名访问博士生，来英已近一年，虽然短暂，却收获了人生最大的意义——发现了生命的光。我的人生是令人羡慕的，又是极其脆弱的，被我小心翼翼地用完美主义和单一的价值观裹挟着，几乎没有什么安全感地向前推进。我会为自己的成就短暂地获得巨大的满足，但安全感的丧失经常将其替代为长久的焦虑、孤独感、迷茫以及对未来的恐惧。我曾一度觉得一切都没有什么意义，做什么事情都是好累、好勉强的，只像在维护一个机器继续转动，不至停下而已。

在这种黑暗中，我来到Bristol，从对教会和基督徒的好奇，开始了我一点点的探索。我起初抱着一种打卡的心态参加各种活动、启发课程、营会，认识基督徒朋友，参加团契，兴奋的背后依然是焦虑甚至勉强；却在这个过程中第一次听见耶稣说：“我是世界的光。跟从我的，就不在黑暗里走，必要得着生命的光。”（约翰福音8:12） 当我开始了解神，神一直带给我很多惊喜，以我完全想不到的方式在我身上动工。在一片神与弟兄姐妹爱的海洋中，神用各种方式向我诉说的话语，在我极其理性、充满逻辑的、学数学与工程的大脑中推理又碰撞，最终让我非但不是自负地驳斥其荒谬，而竟是慢慢扫清横在真理前的各种障碍，反使我更坚定地愿意跟随耶稣基督，让我睁开眼睛看到祂就是道路、真理、生命。我惊奇的发现那束光照亮我的各个角落，没有一个落下，从日常生活、学业、感情、人际交往，到人生观、世界观、价值观。很多人也发现我心智成熟了很多，我更多地明白了什么是爱，更加热爱生活、坦然面对大小事情、并关心他人。其中的一些都是我曾下决心自己改变自己的，但最终发现这些改变并不是凭着我血气地努力，也不是所谓近朱者赤、近墨者黑的无情逻辑，而是单单是因为神的完全掌权和对我的爱。

今天我在回国前受洗，是对我的信心的一个见证，是坚固我信心，也是一个大声宣告：我是一个新造的人，不再是我自己，而是基督在我里面活着。我很感恩神这一年来对我的保守与看顾，让我遇见祂，更重要的是，让我知道我未来的生命在祂里面的无限。回到中国，也许会面临诸多困难：人面临着试探，大环境诱惑着人单一地崇拜那些看得见的权力、金钱与名声；我可能会陷入软弱，被焦虑与恐惧支配，对社会的破碎感到失望，封锁自己并被虚伪的面具驯化，又对信仰闪闪躲躲；也可能会陷入固执与自大，用那套粗暴自私的丛林法则继续支配我追求单一世俗的成功，然后兜兜转转又回到安全感与价值感的洼地。但我深知道，神会用祂的爱与大能说：“你不要害怕，因为我与你同在；不要惊惶，因为我是你的神。我必坚固你，我必帮助你，我必用我公义的右手扶持你。”（以赛亚书41:10） 若我活出耶稣基督的样子，必致更多的人追随祂，领受祂的爱。我的坚信，也必使更多的人信祂，让更多亮光的照进暗淡的角落！

感谢神，谢谢大家的聆听！




# Testimony at CU International Event (24/10/2024)

Hi everyone! My name is Shawn. I’m excited to share my testimony of faith with you. Sorry that I am not very confident in speaking English, so I have to rely on a script.

I am a visiting PhD student from China and only became a Christian several months after I came to the UK. This is my first time abroad, and over the past few months, I’ve found the environment here fascinatingly different. I appreciate the warmth and kindness of people, the work-life balance, the attitudes towards life, the commitment to protecting human rights and the environment, and freedom of speech—some of which are not really a consensus in my home country. I have personally experienced the positive aspects of different societies and cultures and have gained a lot from them during this visiting period. However, if you ask what has had the deepest impact on me, I would say it is the good news from God, also known as the gospel.

Growing up in the Chinese education system, I was the typical student always praised by parents and teachers. I was one of their best models, always efficient and achieving good grades in my studies. I was like a machine, optimizing objective functions (if you know about maths...) toward every goal in every corner of my life with all my effort: the grade of an exam, the chance of admission, how much benefit I could get from a lecture, an event, a trip, even a film, a conversation. When I fell deeper into this state, time was measured by minutes. I even calculated and evaluated the time I spent on eating and never let myself stop and take a break. I should admit that it somehow helped me get into one of the top universities in China, but it also left me with endless nightmares. Anxiety, obsession, and perfectionism became main problems lingering in my mind. It felt like there was no margin for error in my life, like a knife hanging over my head, and I didn’t make the optimal decision, my whole world might come to an end. I was so afraid of losing the material and social possessions I had, not even a small thing. But at the same time, when I didn’t have the energy to start my “optimizer engine,” I couldn’t even get out of bed and would stop my efforts completely. I felt lonely, meaningless, and unsafe. I complained a lot and kept asking why life wasn’t enjoyable for me, and what was the point of living like this. I needed help, but I was too stubborn and insecure to ask for it. I often overestimated my ability to completely manage myself, believing every result was a direct consequence of how well I behaved, reaping what I sowed, nothing to do with anyone else. My parents sometimes saw my vulnerable side and showed great concern. They tried their best, but their encouragement was always like, “Come on, you can get over it! You can do something relaxing and adjust yourself, then get the energy to rise again!” Or, “You’re too good to worry; there are many people who haven’t achieved as much as you; the worst thing that happens to you couldn’t be that bad.” I’d say, “Yes, it makes sense,” but I knew myself—I’d been trapped in this mindset since my school years, and it wasn’t something that could change me.

When I came to the UK, I immediately set another objective function for myself: I must explore British life and culture as much as possible within this short 1-year period. Christianity and church were part of that ambition. I wanted to see how Christian foreigners live, to help me decide on my future or simply to go back and brag to friends... Some of my friends (I mean you guys) might have noticed that during events, I was almost obsessively, nervously trying to absorb as much information as I could and meet as many people as possible. If I couldn’t do everything within the limited time, I tried my best to record it, like taking lots of photos. This was far beyond curiosity—it was an obsession, and similar ambitious plans to explore everything pushed me into a bottomless pit. As I managed my life, research, cooking (since we ate at cheap uni canteens in China), and exploration all at the same time, I felt overwhelmed again, which brought me endless anxiety and an obsession with not exploring enough, causing regret or even fear of making poor decisions in the future, not to mention the real challenges of living abroad on my own for the first time. But very fortunately, God saw my suffering and reached out to me. At a critical moment, when I needed to find new accommodation but couldn’t, I was offered a place at Woodies. My family and I couldn’t help thinking how miraculous it was. During the months I lived there, I naturally got involved with the church, met many of you from CU at Woodies, attended CU events, and went to the Alpha course. There, I found a phenomenon that Christians, regardless of their background or nationality, were far beyond just friendly and polite; they were eager to share the gospel with me. Although I was sometimes confused about new English vocabulary, I sensed that this must be truly good news, as I logically believed that nothing else could make people that enthusiastic to tell others in a non-authoritarian society. Soon, I met some Chinese Christians, and at my first fellowship meeting in Chinese, I suddenly found so many parallels and connections to what I’d seen in English. Everything was astonishingly similar, and cultural differences hardly seemed to matter. I asked a lot of questions, and many things in English that I had partially understood for months were clearly explained that night. That’s when I realized that this is not a Western thing; I felt God was uniting the world.

Then I went to a COCM Christian camp during the Easter holiday and made my commitment prayer to Christ. After returning, I kept thinking about it and consolidating my understanding. But things had already started changing, even when I was still unsure about my faith identity. I stopped selfishly calculating my interests, felt more comfortable helping others, became more open-minded, complained less, and became less cynical. I also began to have a healthier view of family, friends, and romantic love. (Guess what? I used to think of my parents as my bosses! ) But more importantly, the anxiety and inability to enjoy life, which I had struggled with for many years, began to fade. For years, I’d tried many ways to cure myself: the “let it go” oriental philosophy, all kinds of therapy, and Sigmund Freud’s books—they all proved not to work for me and let me down. I would never have imagined that Christianity could help, but it did. When I prayed and brought myself to the Father, I heard a voice saying, “You are my son, and you are loved; don’t worry.” I realized that the problems I suffered from were because I didn’t know God and didn’t recognize both my limitations and His almighty power.

I still remember how the verse in Matthew, “For my yoke is easy and my burden is light,” brought me so much peace and eased the pain of my constant feelings of insecurity. But now I won’t use the word “work,” because God is not a tool or therapist, as many people back in my home believe. He is the truth. Truth is consistent. It is not about practicality or optimization, which only causes inner conflict in people’s hearts, making people focus solely on work and personal interests, sharing no love with others and the world. Truth is an unchanging principle that gives your life value and eternity, without the need to worry, unlike human authorities who convince you of their truth but then let you down by constantly changing their rules. Truth is almighty. It unravels the knots in your heart that not even your parents could untie, the ones you thought were the end of the world.

I truly felt I am a creation of God and loved by Him. My journey to faith is also very logical. Getting to know God was like how a math student thinks and reasons, constructing a logical system and solving the final unanswered questions. Eventually, the towering tree of faith sprouted and began to grow. I know some might gossip about Christianity—that it takes advantage of people when they are down and touches them emotionally—but my experience proves that God can melt even a stubborn mind like mine. Why? Because our Father made me this way. He is in control of it all, and He loves every unique aspect of His children. Look at me! Even my anxious curiosity, the motivation I once denied as a good thing and thought was the source of my anxiety—was exactly the character that led me to approach faith. Isn’t that amazing?

Now, I’ve committed to Bristol Chinese Gospel Church, a fairly new Mandarin-speaking church with a vision to let more Chinese students hear the good news of God. I think God calls me to be here, as I understand how Chinese students think and what they need, because we come from the same educational and cultural background. Although the familiar environment wasn’t part of my grand exploration plan and could interfere with my time to explore new things, this is something I decided to commit to but never expected. And now, I no longer feel like a visitor or a foreigner in faith. Even though I don’t have much time left to stay here, I feel that this is my home—I am a child of God.

I encourage you to explore the good news of God, and I want to say that we all have stereotypes and strong ideologies about things, especially about Christianity, particularly if you’re from Mainland China. But don’t be afraid to explore; don’t be afraid to ask questions. It is not hostile, and it is certainly not a tool of Western governments to manipulate minds. Don’t label yourself as ‘not that kind of person,’ or think you’re unqualified, or feel that this isn’t your culture. God loves everyone, and He is the truth without conditions. There is no difference in God’s eyes between your real-life circumstances, your culture, or your language, but there is a difference between not knowing God, and knowing God and surrendering to Him.

Thank you!