---
title: "Bacon Lardons"
date: "2024-07-22"
draft: true
toc: true

categories: [cooking]
---


# Varieties

# Simplest Cooking

1. Raw cooking
 1. Wash before use
**2. Steamed**
• **Plain**: Steam broccoli until tender and sprinkle with a little salt and pepper.
• **Seasoned**: Steam and then toss with olive oil, lemon juice, garlic, and a pinch of red pepper flakes.
**3. Boiled**
• **Lightly Boiled**: Boil broccoli in salted water for 2-3 minutes until tender-crisp, then drain and serve.
• **Blanched**: Boil briefly and then plunge into ice water to preserve its bright green color and crispness. Great for salads and cold dishes.
**4. Oven (Roasted vegetable)**
• **Simple Roasted**: Toss broccoli florets with olive oil, salt, and pepper, and roast in the oven at 400°F (200°C) for about 20 minutes, until edges are crispy.
• **Garlic Parmesan**: Add minced garlic and grated Parmesan cheese before roasting for extra flavor.
**Stir-Fried**
• **Basic Stir-Fry**: Stir-fry broccoli in a hot pan with a bit of oil, garlic, and soy sauce.

**6. Grilled*
• **Grilled Broccoli**: Toss with olive oil, salt, and pepper, and grill on medium heat until charred and tender, about 5-7 minutes.

• **Grilled Skewers**: Skewer broccoli with other vegetables and grill for a tasty side dish.

::: {.callout-tip title="Cooking Tips"}:::
-

# Classic Dishes

 1. Broccoli Cheddar soup:

**7. Soups*
• **Broccoli Cheddar Soup**: Cook broccoli with onions and chicken or vegetable broth, then blend with cheddar cheese for a creamy soup.

• **Pureed Broccoli Soup**: Blend cooked broccoli with broth and seasonings for a smooth, healthy soup.
 2.  Casseroles and Bakes**
• **Broccoli Casserole**: Mix steamed broccoli with a creamy sauce, cheese, and breadcrumbs, and bake until golden and bubbly.
• **Broccoli and Rice Bake**: Combine cooked rice, broccoli, cheese, and a creamy sauce, then bake until heated through.
• **Mixed Vegetables**: Combine with other vegetables like bell peppers, carrots, and snap peas in a stir-fry.
**9. Pasta and Grain Dishes**
• **Pasta Primavera**: Add steamed or roasted broccoli to pasta along with other vegetables and a light sauce.
• **Quinoa or Rice Bowl**: Mix cooked broccoli into quinoa or rice bowls with other ingredients like beans, avocado, and a tangy dressing.

# Innovative Dishes

1. n
**10. Broccoli Pesto**
**11. Smoothies**
• **Green Smoothie**: Add a small amount of raw or lightly steamed broccoli to your green smoothie along with fruits like banana and apple, and a liquid base like almond milk.
• **Broccoli Pesto**: Blend steamed broccoli with basil, garlic, nuts, Parmesan cheese, and olive oil to make a healthy pesto sauce for pasta or as a spread.

# Storage


- Place: cool, dry place from direct sunlight
- Once opened:
- Freezable:
- Once frozen:

