---
title: Ceilidh Dances Calling (Chinese)
description: "Calling scripts in Chinese for Ceilidh dances I know. Useful for Ceilidh callers to learn."
date: 2024-12-20
draft: false
categories: [music, Chinese]
number-sections: true
---

一些 Ceilidh 舞的跳法笔记, 供领舞员 (caller) 学习参考. 


## 飞翔的苏格兰人 (Flying Scotsman)

{{< video https://www.youtube.com/embed/jyVX0F95M5w >}}

**阵型:**

- 每组 8 个人, 站成 2 队, 每队 4 个人, 面对面. (可以按性别分, 称为男生队/女生队)
- 组之间纵向连接, 形成长走廊, 指向台上. 

**音乐:** Reel, 速度要快. 最好 32小节 (AABB), 因为是一个循环, 结束不会突兀. 

**动作:** 

- 1-8小节: 第一对 (最靠近台上的) 面对面手拉手跳向走廊尽头; 往回跳回原组的末端位置. 组内其他人向靠近台上串一个位置, 为这一对往回跳留出空间; 可以拍手; 
- 9-16小节: 男生队手拉手抬起来形成拱门不动, 女生队手拉手由第一个人带领, 从拱门下蜿蜒穿过, 绕回原位置;
- 17-24小节: (反过来) 女生队手拉手抬起来形成拱门不动, 男生队手拉手由第一个人带领, 从拱门下蜿蜒穿过, 绕回原位置;
- 25-32小节: 所有对手拉手, 向走廊尽头跳, 往回跳回原位置.


## 幸运七 (Lucky Seven)

{{< video https://www.youtube.com/embed/E7VHA_prLok >}}

**阵型:**

- 偶数个人, 所有人围成一圈. 每个人报数1或2. 


**音乐:** Reel 或 Jig, 速度快. 最好 32 小节 (AABB), 因为是一个循环, 结束不会突兀. 

**动作:**

- 1-8小节: 所有人手拉手, 向右走七步, 顺时针转圈; 再向左走七步, 逆时针转圈;
- 9-16小节: 所有人向前走七步, 踢一下; 再向后走七步, 回到原位置;
- 17-24小节: 所有人向右走七步, 顺时针转圈; 再向左走七步, 逆时针转圈;
- 25-32小节: 1 号向右转伸出右手, 2 号向右转伸出左手, 相握后向前越过对方, 伸出左手, 与下一个人相握后再越过. 如此交替进行, 重复 4 次. 





## 剥柳树 (Strip the Willow)


{{< video https://www.youtube.com/embed/B2C3UnanPQ0 >}}

**阵型:**

- 2 条长队伍, 每队最少 4 个人, 面对面.

**音乐:**  Jig, 速度快. 因为人数不固定, 所以不要求特定小节数.



**动作:**

- 1-8小节: 第一对 (最靠近台上的) 交叉起来手拉手, 转圈;
- 9-16小节: 第一对每个人伸出右手臂, 第二对也是, 肘关节相连, 分别一起转圈; 转回后, 第一对每个人伸出左手臂, 肘关节相连, 转圈;
- 17小节后: 对第三、四、...对重复9-16小节, 直到队尾. 其他人可以拍手, 在中间可以适当向靠近台上串位置. 此时的第一队可以按照相同方式开始了.




## 弗吉尼亚里尔舞 (Virginia Reel)

{{< video https://www.youtube.com/embed/gnLEnf-6S_U >}}

**阵型:**

- 每组 8 个人, 站成 2 队, 每队 4 个人, 面对面. (可以按性别分)

**音乐:** Reel, 速度适中. 因为人数不固定, 所以不要求特定小节数.

**动作:**

- 1-8小节: 每个人向前走四步, (可以与对方击掌) 再向后走四步, 重复两次;
- 9-16小节: 每一对右手臂肘部相连, 转圈; 再左手臂肘部相连, 转圈;
- 17-24小节: 每一堆手拉手转圈; 再向前走到对方身后, 背靠背, 再回到原位置;
- 25-32小节: 第一对 (最靠近台上的) 面对面手拉手跳向走廊尽头; 往回跳回原组的末端位置. 
- 33小节后: 第一对做 strip the willow 的动作, 到队尾后, 再手拉手跳回来. 第一对带领自己的队向外绕向队尾, 第一对在队尾双手结合形成拱形, 其他人从拱门下穿过, 绕回原位置.
