---
title: Piano accompaniment
description: An introduction notebook.
date: 2024-07-27
draft: true
image: false
toc: false
categories: [music, English]
format:
  html:
    include-in-header:
      - text: <script src="https://www.abcjs.net/abcjs-plugin-min.js" type="text/javascript"></script>
      - text: |
          <script>
          document.addEventListener('DOMContentLoaded', (event) => {
              let elements = document.querySelectorAll('.abctext');
              elements.forEach(element => {
                  element.style.display = 'none';
              });
          });
          </script>
    css: ../topics/songbook/assets/abcjs.css

---

I am interested in music theory a lot, but haven't got any time or opportunity to do some practical exercises on piano.  I could do on guitar (just strumming chords) or accordion, but they are quite different in terms of many aspects.

I've got the chance to serve as a piano player in the church several weeks ago. The worship songs are quite simple and they are usually classified as [Christian Pop](https://en.wikipedia.org/wiki/Contemporary_Christian_music) or simply [C-Pop](https://en.wikipedia.org/wiki/C-pop) for Chinese songs, and the piano is supposed to be an accompaniment rather than solo, which is exactly what I want to learn at the moment. Apart from that, the practice in the church service that involves interacting with other instruments, the congregation and narrating pastor, is a really efficient way to get familiar with the keyboard and stage performing. I really appreciate this opportunity and I've been learning how to do this theoretically by myself (mostly through the [CWY Worship](https://www.youtube.com/c/CWYWORSHiP) channel) and putting into practice in several worship songs (where you can find in my [songbook](../topics/songbook/index.qmd)).

Let's get started!

# General Ideas

The core of piano accompaniment is to play chords with right hand, while piano solo to play melodies with right hand. Playing melodies is nothing wrong but it's not "accompaniment" technically and definitely disturbs the vocals.

As for left hand, do remember that neither accompaniment nor solo play chords like what it is with right hand, because chords sound really muddy when denser notes are played in lower ranges. Left hand is usually meant for sparser notes like root and fifth.

We have to learn some patterns for both hands and put them together later. But before we go there, I need to know and practice an absolute basic for any piano playing which I haven't learned before — the pedals.

# Sustain Pedal

Sustain pedal creates a legato sound for notes. As we want the piano sounds continuous, **we hold the pedal down by default**. But at the moment when chord changes, it sounds muddy and perhaps dissonant because the previous chord is sustained to overlap with the next chord, so keep in mind **resetting the sustain at the point of chord change**.

The reset action is to **release the pedal and press again at once**. The timing is really important. Release the pedal after the chord change moment, rather than before. The motion of your hands and foot should be opposite, which means release (upwards) the pedal by foot while play (downwards) the next chord by hands.

A few tips on this:
- Take it as you are diving. Pressing the pedal is like holding your breath, and reset action is like taking a breath between phrases.
- If you try to use some formula, you can try "quick-up-and-down, 2, 3, 4" as a substitute for your beat counting "1, 2, 3, 4".
- Move your foot a bit forward, covering more of the pedal.  That makes you use less force and feel comfortable to hold the pedal down as it is the default position.
- Don't lift your foot off the pedal when releasing as we don't want the unpleasant sound.

We should practice a lot and make it natural and comfortable like your breath of the pedal reset, as it's used a lot and we don't have a spare mind to think about it especially in an interacting occasion like church service. Check out this[ video](https://www.youtube.com/watch?v=FyafaUMwSZo) for practice by CWY worship.


# Left Hand


## Block Chords

What I used to do

Works for solo. Should be really high pitch for left hand to avoid muddy. In this case, don't care the root. Use inversions to avoid jump around.

As I mentioned above, left hand is for root and fifth notes avoiding using thirds as it shouldn't sound muddy. It could be:


- A root note (1);
- Stacked octave (1-8);
- Stacked fifth (1-5): if there is no enough space for octave
- All (1-5-8)




# Right Hand

The right hand plays the chords. For triads, we play stacked "1-3-5" by default, but usually apply lots of chord Inversions as they are very helpful for least finger moving.

# Pattern Together

If we combine both hands together, we have a series of pattern for accompaniment.  Here are some handy patterns for different kinds of music, slow or fast, happy or moody.

## fenjie
不要太低

123456: 1 chord in one bar
```
X:1
V: R
Q: 4/4
[CEG]3EG2c2|
V: L clef=bass
C,G, Cz z2|
```


- 齊五八七五八: 2 chord in one bar
```
X:1
V: R
Q: 4/4
[CEG]4[CEG]4|
V: L clef=bass
C,,G,,C,2C,,G,,C,2|
```

## dd


齊右右右:
```
X:1
V: R
Q: 4/4
[CEG]2[CEG]2[CEG]2[CEG]2|
V: L clef=bass
[C,,C,]8|
```
- 齊 右左 齊 右
```
X:1
V: R
Q: 4/4
[CEG]2[CEG]2[CEG]2[CEG]2|
V: L clef=bass
[C,,C,]3[C,,C,][C,,C,]4|
```


- 齊5、8大、小、中
```
X:1
V: R
Q: 4/4
[CEG]3CG2E2|
V: L clef=bass
C,,G,,C,6|
```


- 齊左齊左


#d


## Faster

For faster songs, imitating drums.

左右 左左右
```
X:1
V: R
Q: 4/4
z2[CEG]2z2[CEG]2|
V: L clef=bass
[C,,C,]4[C,,C,][C,,C,]z2|
```




左 右左 空左右
```
X:1
V: R
Q: 4/4
z2[CEG]2z2[CEG]2|
V: L clef=bass
[C,,C,]3[C,,C,]z[C,,C,]3|
```


左右左 左右: 比較可愛
```
X:1
V: R
Q: 4/4
z2[CEG]2z2[CEG]2|
V: L clef=bass
[C,,C,]3[C,,C,][C,,C,]2z2|
```


左右左右左右左右
```
X:1
V: R
Q: 4/4
z[CEG]z[CEG]z[CEG]z[CEG]|
V: L clef=bass
[C,,C,]2[C,,C,]2[C,,C,]2[C,,C,]2|
```



## Transition Variation

 Usually The bar before chorus. or big changing

```
X:1
V: R
Q: 4/4
[CEG]2 [CEG]2 [CEG][CEG]  [CEG]2|
V: L clef=bass
[C,,C,]2 [C,,C,]2 [C,,C,][C,,C,] [C,,C,]2|
```


```
X:1
V: R
Q: 4/4
[CEG][CEG]  [CEG]2 [CEG][CEG]  [CEG]2|
V: L clef=bass
[C,,C,][C,,C,] [C,,C,]2 [C,,C,][C,,C,] [C,,C,]2|
```

```
X:1
V: R
Q: 4/4
z [CEG] [CEG][CEG] [CEG][CEG]  [CEG]2|
V: L clef=bass
z [C,,C,] [C,,C,][C,,C,] [C,,C,][C,,C,] [C,,C,]2|
```

```
X:1
V: R
Q: 4/4
z [CEG]2 [CEG][CEG][CEG][CEG]|
V: L clef=bass
z [C,,C,]2 [C,,C,][C,,C,][C,,C,][C,,C,]|
```

## Variations

 Usually every 2 bars

1XXX| 2XXY | 3XXX| 4XYY|

Y = 1/8 1/8 any notes in chords right hand

# Intro

solo melody in right hand

15858585  left hand


